stages:
  - deploy

variables:
  CURRENT_BRANCH: $CI_COMMIT_REF_NAME

before_script:
  - source /home/gitlab-runner/.bashrc
  - npm install pm2 -g

start-staging:
  stage: deploy
  tags:
    - usastaging
  script:
    - make start-mailer-staging
  only:
    - staging

start-prod:
  stage: deploy
  tags:
    - tonic3-aws
  script:
    - make start-mailer-prod
  only:
    - master
